# Generated by Django 2.1.2 on 2019-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('rate', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('track_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
